// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3Use8UDu1RocBdCgaE4S6RIyRdjUyP78',
    appId: '1:767147460377:web:cea7f7e34603af48672788',
    messagingSenderId: '767147460377',
    projectId: 'evently-a09b4',
    authDomain: 'evently-a09b4.firebaseapp.com',
    storageBucket: 'evently-a09b4.firebasestorage.app',
    measurementId: 'G-2Y1BPJ0330',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDZDK4Mk7s-Op5IUId1BzfGTsAo72gwPo',
    appId: '1:767147460377:android:5ddd14a4567f0de6672788',
    messagingSenderId: '767147460377',
    projectId: 'evently-a09b4',
    storageBucket: 'evently-a09b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJQfra7mcmkRhPKSLoraYrBibtT0ByBE8',
    appId: '1:767147460377:ios:fbee00981a3e62de672788',
    messagingSenderId: '767147460377',
    projectId: 'evently-a09b4',
    storageBucket: 'evently-a09b4.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJQfra7mcmkRhPKSLoraYrBibtT0ByBE8',
    appId: '1:767147460377:ios:fbee00981a3e62de672788',
    messagingSenderId: '767147460377',
    projectId: 'evently-a09b4',
    storageBucket: 'evently-a09b4.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3Use8UDu1RocBdCgaE4S6RIyRdjUyP78',
    appId: '1:767147460377:web:b8ece12f7fe73962672788',
    messagingSenderId: '767147460377',
    projectId: 'evently-a09b4',
    authDomain: 'evently-a09b4.firebaseapp.com',
    storageBucket: 'evently-a09b4.firebasestorage.app',
    measurementId: 'G-SPGXHSWDNX',
  );
}
